# Generated by Django 4.0.6 on 2022-08-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('start_dt', models.DateField(verbose_name='START_DATE')),
                ('end_dt', models.DateField(verbose_name='END_DATE')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='TIME')),
                ('place', models.CharField(max_length=100, verbose_name='PLACE')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Latitude')),
                ('log', models.DecimalField(decimal_places=20, max_digits=30, verbose_name='longitude')),
                ('trip_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.upload')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
